export const config = {
  baseUrl: "https://appeditor.xyz/",
  ck: "ck_9ee0259cfdd2096f33a88f34ba842f1acc61ed4e",
  cs: "cs_3d966a86be1fe30f93126740dd06b40adaa6c040",
  appSlug: "woostore",
  colorMode: "light",
  colorTheme: {
    "color-primary-100": "#FEE6D2",
    "color-primary-200": "#FEC7A6",
    "color-primary-300": "#FCA07A",
    "color-primary-400": "#F97B58",
    "color-primary-500": "#F54023",
    "color-primary-600": "#D22419",
    "color-primary-700": "#B01114",
    "color-primary-800": "#8E0B17",
    "color-primary-900": "#75061A",
    "color-success-100": "#EAFDDA",
    "color-success-200": "#D0FCB6",
    "color-success-300": "#AEF790",
    "color-success-400": "#8DEF73",
    "color-success-500": "#5CE547",
    "color-success-600": "#3BC433",
    "color-success-700": "#23A426",
    "color-success-800": "#168422",
    "color-success-900": "#0D6D1F",
    "color-info-100": "#CCF0FE",
    "color-info-200": "#99DDFE",
    "color-info-300": "#66C4FD",
    "color-info-400": "#40AAFB",
    "color-info-500": "#0282F9",
    "color-info-600": "#0164D6",
    "color-info-700": "#014AB3",
    "color-info-800": "#003490",
    "color-info-900": "#002577",
    "color-warning-100": "#FDF9CC",
    "color-warning-200": "#FCF29A",
    "color-warning-300": "#F8E667",
    "color-warning-400": "#F1D940",
    "color-warning-500": "#E8C606",
    "color-warning-600": "#C7A704",
    "color-warning-700": "#A78903",
    "color-warning-800": "#866C01",
    "color-warning-900": "#6F5701",
    "color-danger-100": "#FDE8D6",
    "color-danger-200": "#FCCBAD",
    "color-danger-300": "#F8A684",
    "color-danger-400": "#F28264",
    "color-danger-500": "#EA4C33",
    "color-danger-600": "#C92E25",
    "color-danger-700": "#A8191C",
    "color-danger-800": "#87101C",
    "color-danger-900": "#70091C",
  },
  pages: [
    {
      name: "Home",
      icon: {
        provider: "material",
        name: "home",
        size: 24,
        activeColor: "tomato",
        inactiveColor: "gray",
      },
      navPriority: 1,
      addToBottomNav: false,
      showHeaderBar: false,
      json: '{"ROOT":{"type":{"resolvedName":"Container"},"isCanvas":true,"props":{"style":{"flexDirection":"column","flex":1},"scrollable":true},"displayName":"Container","custom":{},"hidden":false,"nodes":["PnU73d5i7","jB8HBnqeG","KoZd3lbe4","guv_b2ZX6"],"linkedNodes":{}},"jB8HBnqeG":{"type":{"resolvedName":"GridPost"},"isCanvas":true,"props":{"numColumns":1,"postQuery":{},"showsHorizontalScrollIndicator":false,"style":{"padding":16},"postType":"post","horizontal":true},"displayName":"GridPost","custom":{},"parent":"ROOT","hidden":false,"nodes":["adRh_K8S7"],"linkedNodes":{}},"adRh_K8S7":{"type":{"resolvedName":"Container"},"isCanvas":true,"props":{"style":{"flexDirection":"column","padding":0,"borderRadius":8,"borderWidth":1,"borderColor":"#f1f1f1","marginBottom":0,"width":200,"marginRight":16,"height":240},"onPressAction":["navigate"],"navigateTo":"post-detail"},"displayName":"Container","custom":{},"parent":"jB8HBnqeG","hidden":false,"nodes":["PMRWUjgRo","Rnaep-6hp"],"linkedNodes":{}},"PMRWUjgRo":{"type":{"resolvedName":"Image"},"isCanvas":false,"props":{"postContent":"featured_image","style":{"width":"100%","height":160,"borderTopLeftRadius":8,"borderTopRightRadius":8}},"displayName":"Image","custom":{"postType":"post"},"parent":"adRh_K8S7","hidden":false,"nodes":[],"linkedNodes":{}},"Rnaep-6hp":{"type":{"resolvedName":"Text"},"isCanvas":false,"props":{"postContent":"title","isHtml":false,"title":"Text","category":"s1","status":"basic","style":{"textAlign":"center","marginTop":16,"marginBottom":16,"margin":8}},"displayName":"Text","custom":{"postType":"post","postTypeContent":"post"},"parent":"adRh_K8S7","hidden":false,"nodes":[],"linkedNodes":{}},"guv_b2ZX6":{"type":{"resolvedName":"GridPost"},"isCanvas":true,"props":{"numColumns":1,"postQuery":{"categories":0,"order":"desc","orderby":"title"},"showsHorizontalScrollIndicator":false,"style":{"padding":16},"postType":"post","horizontal":false},"displayName":"GridPost","custom":{},"parent":"ROOT","hidden":false,"nodes":["jjM2UKUsd0"],"linkedNodes":{}},"jjM2UKUsd0":{"type":{"resolvedName":"Container"},"isCanvas":true,"props":{"style":{"flexDirection":"column","padding":0,"borderRadius":8,"borderWidth":1,"borderColor":"#f1f1f1","marginBottom":16,"width":"100%","marginRight":16},"onPressAction":["navigate"],"navigateTo":"post-detail"},"displayName":"Container","custom":{},"parent":"guv_b2ZX6","hidden":false,"nodes":["k8E0bMbxuM","NW_uehUP3J"],"linkedNodes":{}},"k8E0bMbxuM":{"type":{"resolvedName":"Image"},"isCanvas":false,"props":{"postContent":"featured_image","style":{"width":"100%","height":160,"borderTopLeftRadius":8,"borderTopRightRadius":8}},"displayName":"Image","custom":{"postType":"post"},"parent":"jjM2UKUsd0","hidden":false,"nodes":[],"linkedNodes":{}},"NW_uehUP3J":{"type":{"resolvedName":"Text"},"isCanvas":false,"props":{"postContent":"title","isHtml":false,"title":"Text","category":"s1","status":"basic","style":{"textAlign":"center","marginTop":16,"marginBottom":16,"margin":8}},"displayName":"Text","custom":{"postType":"post","postTypeContent":"post"},"parent":"jjM2UKUsd0","hidden":false,"nodes":[],"linkedNodes":{}},"PnU73d5i7":{"type":{"resolvedName":"Text"},"isCanvas":false,"props":{"postContent":"disable","isHtml":false,"title":"Recent Blogs","category":"h2","status":"basic","style":{"margin":16,"marginBottom":0}},"displayName":"Text","custom":{},"parent":"ROOT","hidden":false,"nodes":[],"linkedNodes":{}},"KoZd3lbe4":{"type":{"resolvedName":"Text"},"isCanvas":false,"props":{"postContent":"disable","isHtml":false,"title":"Popular Blogs","category":"h2","status":"basic","style":{"margin":16,"marginBottom":0}},"displayName":"Text","custom":{},"parent":"ROOT","hidden":false,"nodes":[],"linkedNodes":{}}}',
      slug: "home",
    },
    {
      name: "Post Detail",
      icon: {
        provider: "material",
        name: "home",
        size: 24,
        activeColor: "tomato",
        inactiveColor: "gray",
      },
      navPriority: 1,
      addToBottomNav: false,
      showHeaderBar: true,
      json: '{"ROOT":{"type":{"resolvedName":"Container"},"isCanvas":true,"props":{"style":{"flexDirection":"column","flex":1},"scrollable":true},"displayName":"Container","custom":{},"hidden":false,"nodes":["vlzW-Om84"],"linkedNodes":{}},"vlzW-Om84":{"type":{"resolvedName":"SinglePost"},"isCanvas":false,"props":{"postType":"post"},"displayName":"Single Post","custom":{},"parent":"ROOT","hidden":false,"nodes":[],"linkedNodes":{"single-post-container":"NsHJE8Gzy"}},"NsHJE8Gzy":{"type":{"resolvedName":"Container"},"isCanvas":true,"props":{"style":{"flexDirection":"column","padding":0}},"displayName":"Container","custom":{},"parent":"vlzW-Om84","hidden":false,"nodes":["zFNESiG94","P8iyR4ixb"],"linkedNodes":{}},"zFNESiG94":{"type":{"resolvedName":"Image"},"isCanvas":false,"props":{"postContent":"featured_image","style":{"width":"100%","height":240}},"displayName":"Image","custom":{"postType":"post"},"parent":"NsHJE8Gzy","hidden":false,"nodes":[],"linkedNodes":{}},"2m3yWwzOh":{"type":{"resolvedName":"Text"},"isCanvas":false,"props":{"postContent":"title","isHtml":false,"title":"Text","category":"h4","status":"basic","style":{}},"displayName":"Text","custom":{"postType":"post","postTypeContent":"post"},"parent":"P8iyR4ixb","hidden":false,"nodes":[],"linkedNodes":{}},"4ghFOyOPq":{"type":{"resolvedName":"Text"},"isCanvas":false,"props":{"postContent":"content","isHtml":true,"title":"Text","category":"p1","status":"basic","style":{}},"displayName":"Text","custom":{"postType":"post","postTypeContent":"post"},"parent":"P8iyR4ixb","hidden":false,"nodes":[],"linkedNodes":{}},"P8iyR4ixb":{"type":{"resolvedName":"Container"},"isCanvas":true,"props":{"style":{"flexDirection":"column","padding":16}},"displayName":"Container","custom":{},"parent":"NsHJE8Gzy","hidden":false,"nodes":["2m3yWwzOh","4ghFOyOPq"],"linkedNodes":{}}}',
      slug: "post-detail",
      dynamicTitle: true,
    },
  ],
};
